drop table if exists public.active_chat cascade;
drop table if exists public.incomes cascade;
drop table if exists public.spends cascade;

create table public.active_chat (id int8 generated by default as identity, chat_id int8, primary key (id));
create table public.incomes (id int8 generated by default as identity, chat_id int8, income numeric(19, 2), primary key (id));
create table public.spends (id int8 generated by default as identity, chat_id int8, spend numeric(19, 2), primary key (id));